name: Build Workflow

on:
  push:
    branches: 
      - develop
      - release-*
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (development or staging or production)'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
  

jobs:
  deploy-development:
    name: Deploy Development Build and Push
    environment: development
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'development')
    runs-on: ubuntu-latest
    
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      # Get short commit id
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha 
